/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>

#include "s21_matrix.h"

START_TEST(s21_create_test1) {
  matrix_t A;
  int my_error = s21_create_matrix(1, 1, &A);
  int orig_error = 0;
  s21_remove_matrix(&A);
  ck_assert_int_eq(my_error, orig_error);
}
END_TEST

START_TEST(s21_create_test2) {
  matrix_t A;
  int my_error = s21_create_matrix(9, 9, &A);
  int orig_error = 0;
  s21_remove_matrix(&A);
  ck_assert_int_eq(my_error, orig_error);
}
END_TEST

START_TEST(s21_create_test3) {
  matrix_t A;
  int my_error = s21_create_matrix(1, 15, &A);
  int orig_error = 0;
  s21_remove_matrix(&A);
  ck_assert_int_eq(my_error, orig_error);
}
END_TEST

START_TEST(s21_create_error_test1) {
  matrix_t A;
  int my_error = s21_create_matrix(0, 3, &A);
  int orig_error = 1;
  s21_remove_matrix(&A);
  ck_assert_int_eq(my_error, orig_error);
}
END_TEST

START_TEST(s21_create_error_test2) {
  matrix_t A;
  int my_error = s21_create_matrix(3, -3, &A);
  int orig_error = 1;
  s21_remove_matrix(&A);
  ck_assert_int_eq(my_error, orig_error);
}
END_TEST

START_TEST(s21_equal_test1) {
  matrix_t A, B;
  int my_error_1 = s21_create_matrix(1, 1, &A);
  A.matrix[0][0] = 1.1234567;
  int my_error_2 = s21_create_matrix(1, 1, &B);
  B.matrix[0][0] = 1.1234567;
  ck_assert_int_eq(s21_eq_matrix(&A, &B), SUCCESS);
  ck_assert_int_eq(my_error_1, 0);
  ck_assert_int_eq(my_error_2, 0);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_equal_test2) {
  matrix_t A, B;
  int my_error_1 = s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1.1;
  A.matrix[0][1] = 2.1;
  A.matrix[0][2] = 3.1;
  A.matrix[1][0] = 1.1;
  A.matrix[1][1] = 1.2;
  A.matrix[1][2] = 1.3;
  A.matrix[2][0] = 1.1;
  A.matrix[2][1] = 2.1;
  A.matrix[2][2] = 3.1;
  int my_error_2 = s21_create_matrix(3, 3, &B);
  B.matrix[0][0] = 1.1;
  B.matrix[0][1] = 2.1;
  B.matrix[0][2] = 3.1;
  B.matrix[1][0] = 1.1;
  B.matrix[1][1] = 1.2;
  B.matrix[1][2] = 1.3;
  B.matrix[2][0] = 1.1;
  B.matrix[2][1] = 2.1;
  B.matrix[2][2] = 3.1;
  ck_assert_int_eq(s21_eq_matrix(&A, &B), SUCCESS);
  ck_assert_int_eq(my_error_1, 0);
  ck_assert_int_eq(my_error_2, 0);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_equal_test3) {
  matrix_t A, B;
  int my_error_1 = s21_create_matrix(2, 3, &A);
  A.matrix[0][0] = 1.1;
  A.matrix[0][1] = 2.1;
  A.matrix[0][2] = 3.1;
  A.matrix[1][0] = 1.1;
  A.matrix[1][1] = 1.2;
  A.matrix[1][2] = 1.3;
  int my_error_2 = s21_create_matrix(3, 3, &B);
  B.matrix[0][0] = 1.1;
  B.matrix[0][1] = 2.1;
  B.matrix[0][2] = 3.1;
  B.matrix[1][0] = 1.1;
  B.matrix[1][1] = 1.2;
  B.matrix[1][2] = 1.3;
  B.matrix[2][0] = 1.1;
  B.matrix[2][1] = 2.1;
  B.matrix[2][2] = 3.1;
  ck_assert_int_eq(s21_eq_matrix(&A, &B), FAILURE);
  ck_assert_int_eq(my_error_1, 0);
  ck_assert_int_eq(my_error_2, 0);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_equal_test4) {
  matrix_t A, B;
  int my_error_1 = s21_create_matrix(2, 3, &A);
  A.matrix[0][0] = 1.1234567;
  A.matrix[0][1] = 2.7654321;
  A.matrix[0][2] = 3.1234567;
  A.matrix[1][0] = -1.1234567;
  A.matrix[1][1] = 1.234567;
  A.matrix[1][2] = -1.34567;
  int my_error_2 = s21_create_matrix(2, 3, &B);
  B.matrix[0][0] = 1.1234567;
  B.matrix[0][1] = 2.7654321;
  B.matrix[0][2] = 3.1234567;
  B.matrix[1][0] = -1.1234567;
  B.matrix[1][1] = 1.234567;
  B.matrix[1][2] = -1.34567;
  ck_assert_int_eq(s21_eq_matrix(&A, &B), SUCCESS);
  ck_assert_int_eq(my_error_1, 0);
  ck_assert_int_eq(my_error_2, 0);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_equal_test5) {
  matrix_t A, B;
  int my_error_1 = s21_create_matrix(2, 3, &A);
  A.matrix[0][0] = -1.1234567;
  A.matrix[0][1] = 2.7654321;
  A.matrix[0][2] = -3.1234567;
  A.matrix[1][0] = -1.1234567;
  A.matrix[1][1] = 1.234567;
  A.matrix[1][2] = -1.34567;
  int my_error_2 = s21_create_matrix(2, 3, &B);
  B.matrix[0][0] = 1.1234567;
  B.matrix[0][1] = 2.7654321;
  B.matrix[0][2] = 3.1234567;
  B.matrix[1][0] = -1.1234567;
  B.matrix[1][1] = 1.234567;
  B.matrix[1][2] = -1.34567;
  ck_assert_int_eq(s21_eq_matrix(&A, &B), FAILURE);
  ck_assert_int_eq(my_error_1, 0);
  ck_assert_int_eq(my_error_2, 0);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_equal_test6) {
  matrix_t A, B;
  int my_error_1 = s21_create_matrix(4, 4, &A);
  A.matrix[0][0] = 1111111111111.111111;
  A.matrix[0][1] = 1111111111111.000111;
  A.matrix[0][2] = 1111111111111.000001;
  A.matrix[0][3] = 1111111111111.0;
  A.matrix[1][0] = 7.0;
  A.matrix[1][1] = 7.005;
  A.matrix[1][2] = 7.155;
  A.matrix[1][3] = 7.555;
  A.matrix[2][0] = 4556669932.356568;
  A.matrix[2][1] = 4556669932.123456;
  A.matrix[2][2] = 4556669932.01;
  A.matrix[2][3] = 45.0000001;
  A.matrix[3][0] = 13;
  A.matrix[3][1] = 7;
  A.matrix[3][2] = 3;
  A.matrix[3][3] = 11;
  int my_error_2 = s21_create_matrix(4, 4, &B);
  B.matrix[0][0] = 1111111111111.111111;
  B.matrix[0][1] = 1111111111111.00111;
  B.matrix[0][2] = 1111111111111.000001;
  B.matrix[0][3] = 1111111111111.0;
  B.matrix[1][0] = 7.0;
  B.matrix[1][1] = 7.005;
  B.matrix[1][2] = 7.155;
  B.matrix[1][3] = 7.555;
  B.matrix[2][0] = 4556669932.356568;
  B.matrix[2][1] = 4556669932.123456;
  B.matrix[2][2] = 4556669932.01;
  B.matrix[2][3] = 45.0000001;
  B.matrix[3][0] = 13;
  B.matrix[3][1] = 7;
  B.matrix[3][2] = 3;
  B.matrix[3][3] = 11;
  ck_assert_int_eq(s21_eq_matrix(&A, &B), FAILURE);
  ck_assert_int_eq(my_error_1, 0);
  ck_assert_int_eq(my_error_2, 0);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_equal_test7) {
  matrix_t A, B;
  int my_error_1 = s21_create_matrix(4, 4, &A);
  A.matrix[0][0] = 1111111111111.111111;
  A.matrix[0][1] = 1111111111111.000111;
  A.matrix[0][2] = 1111111111111.000001;
  A.matrix[0][3] = 1111111111111.0;
  A.matrix[1][0] = 7.0;
  A.matrix[1][1] = 7.005;
  A.matrix[1][2] = 7.155;
  A.matrix[1][3] = 7.555;
  A.matrix[2][0] = 4556669932.356568;
  A.matrix[2][1] = 4556669932.123456;
  A.matrix[2][2] = 4556669932.01;
  A.matrix[2][3] = 45.0000001;
  A.matrix[3][0] = 13;
  A.matrix[3][1] = 7;
  A.matrix[3][2] = 3;
  A.matrix[3][3] = 11;
  int my_error_2 = s21_create_matrix(4, 4, &B);
  B.matrix[0][0] = 1111111111111.111111;
  B.matrix[0][1] = 1111111111111.000111;
  B.matrix[0][2] = 1111111111111.000001;
  B.matrix[0][3] = 1111111111111.0;
  B.matrix[1][0] = 7.0;
  B.matrix[1][1] = 7.005;
  B.matrix[1][2] = 7.155;
  B.matrix[1][3] = 7.555;
  B.matrix[2][0] = 4556669932.356568;
  B.matrix[2][1] = 4556669932.123456;
  B.matrix[2][2] = 4556669932.01;
  B.matrix[2][3] = 45.0000001;
  B.matrix[3][0] = 13;
  B.matrix[3][1] = 7;
  B.matrix[3][2] = 3;
  B.matrix[3][3] = 11;
  ck_assert_int_eq(s21_eq_matrix(&A, &B), SUCCESS);
  ck_assert_int_eq(my_error_1, 0);
  ck_assert_int_eq(my_error_2, 0);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_equal_test8) {
  matrix_t A, B;
  int my_error_1 = s21_create_matrix(4, 2, &A);
  A.matrix[0][0] = 3.75;
  A.matrix[0][1] = -5.25;
  A.matrix[1][0] = 3.25;
  A.matrix[1][1] = -5.75;
  A.matrix[2][0] = 3.55;
  A.matrix[2][1] = -5.55;
  A.matrix[3][0] = 3.05;
  A.matrix[3][1] = -5.95;
  int my_error_2 = s21_create_matrix(4, 2, &B);
  B.matrix[0][0] = 3.75;
  B.matrix[0][1] = -5.25;
  B.matrix[1][0] = 3.25;
  B.matrix[1][1] = -5.75;
  B.matrix[2][0] = 3.95;
  B.matrix[2][1] = -5.55;
  B.matrix[3][0] = 3.05;
  B.matrix[3][1] = -5.95;
  ck_assert_int_eq(s21_eq_matrix(&A, &B), FAILURE);
  ck_assert_int_eq(my_error_1, 0);
  ck_assert_int_eq(my_error_2, 0);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_equal_test9) {
  matrix_t A, B;
  int my_error_1 = s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 3.3333333;
  A.matrix[0][1] = -5.25;
  A.matrix[1][0] = 3.25;
  A.matrix[1][1] = 3.3333334;
  int my_error_2 = s21_create_matrix(2, 2, &B);
  A.matrix[0][0] = 3.3333333;
  A.matrix[0][1] = -5.25;
  A.matrix[1][0] = 3.25;
  A.matrix[1][1] = 3.3333335;
  ck_assert_int_eq(s21_eq_matrix(&A, &B), FAILURE);
  ck_assert_int_eq(my_error_1, 0);
  ck_assert_int_eq(my_error_2, 0);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_equal_test10) {
  matrix_t A, B;
  int my_error_1 = s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 3.33333358;
  A.matrix[0][1] = -5.25;
  A.matrix[1][0] = 3.25;
  A.matrix[1][1] = 3.333;
  int my_error_2 = s21_create_matrix(2, 2, &B);
  B.matrix[0][0] = 3.33333359;
  B.matrix[0][1] = -5.25;
  B.matrix[1][0] = 3.25;
  B.matrix[1][1] = 3.333;
  ck_assert_int_eq(s21_eq_matrix(&A, &B), SUCCESS);
  ck_assert_int_eq(my_error_1, 0);
  ck_assert_int_eq(my_error_2, 0);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_sum_test1) {
  matrix_t A, B, result;
  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 0;
  A.matrix[0][1] = 0;
  A.matrix[1][0] = 0;
  A.matrix[1][1] = 0;
  s21_create_matrix(2, 2, &B);
  B.matrix[0][0] = 0;
  B.matrix[0][1] = 0;
  B.matrix[1][0] = 0;
  B.matrix[1][1] = 0;
  int my_error = s21_sum_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      ck_assert_int_eq(result.matrix[i][j], 0);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(s21_sum_test2) {
  matrix_t A, B, result, orig_result;
  s21_create_matrix(3, 2, &A);
  A.matrix[0][0] = 1.0;
  A.matrix[0][1] = 2.0;
  A.matrix[1][0] = 3.0;
  A.matrix[1][1] = 4.0;
  A.matrix[2][0] = 5.0;
  A.matrix[2][1] = 6.0;
  s21_create_matrix(3, 2, &B);
  B.matrix[0][0] = 0.1;
  B.matrix[0][1] = 0.2;
  B.matrix[1][0] = 0.3;
  B.matrix[1][1] = 0.4;
  B.matrix[2][0] = 0.5;
  B.matrix[2][1] = 0.6;
  s21_create_matrix(3, 2, &orig_result);
  orig_result.matrix[0][0] = 1.1;
  orig_result.matrix[0][1] = 2.2;
  orig_result.matrix[1][0] = 3.3;
  orig_result.matrix[1][1] = 4.4;
  orig_result.matrix[2][0] = 5.5;
  orig_result.matrix[2][1] = 6.6;
  int my_error = s21_sum_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_sum_test3) {
  matrix_t A, B, result, orig_result;
  s21_create_matrix(4, 4, &A);
  A.matrix[0][0] = 3;
  A.matrix[0][1] = 33;
  A.matrix[0][2] = -25;
  A.matrix[0][3] = -4;
  A.matrix[1][0] = 8.8;
  A.matrix[1][1] = 3.23;
  A.matrix[1][2] = 4.678;
  A.matrix[1][3] = 10;
  A.matrix[2][0] = -1;
  A.matrix[2][1] = 0;
  A.matrix[2][2] = -33;
  A.matrix[2][3] = 0;
  A.matrix[3][0] = 0;
  A.matrix[3][1] = 88.8;
  A.matrix[3][2] = -2;
  A.matrix[3][3] = 0;
  s21_create_matrix(4, 4, &B);
  B.matrix[0][0] = 10;
  B.matrix[0][1] = 25;
  B.matrix[0][2] = 0.67;
  B.matrix[0][3] = 56;
  B.matrix[1][0] = -11;
  B.matrix[1][1] = -3.23;
  B.matrix[1][2] = 10;
  B.matrix[1][3] = -7;
  B.matrix[2][0] = -2;
  B.matrix[2][1] = 0.33333;
  B.matrix[2][2] = -11.111;
  B.matrix[2][3] = 4;
  B.matrix[3][0] = 56.7;
  B.matrix[3][1] = -22.2;
  B.matrix[3][2] = 0;
  B.matrix[3][3] = 15;
  s21_create_matrix(4, 4, &orig_result);
  orig_result.matrix[0][0] = 13;
  orig_result.matrix[0][1] = 58;
  orig_result.matrix[0][2] = -24.33;
  orig_result.matrix[0][3] = 52;
  orig_result.matrix[1][0] = -2.2;
  orig_result.matrix[1][1] = 0;
  orig_result.matrix[1][2] = 14.678;
  orig_result.matrix[1][3] = 3;
  orig_result.matrix[2][0] = -3;
  orig_result.matrix[2][1] = 0.33333;
  orig_result.matrix[2][2] = -44.111;
  orig_result.matrix[2][3] = 4;
  orig_result.matrix[3][0] = 56.7;
  orig_result.matrix[3][1] = 66.6;
  orig_result.matrix[3][2] = -2;
  orig_result.matrix[3][3] = 15;
  int my_error = s21_sum_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_sum_test4) {
  matrix_t A, B, result, orig_result;
  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 2.4567890;
  A.matrix[0][1] = -5.2869483;
  A.matrix[1][0] = 6.1111335;
  A.matrix[1][1] = -3.9292929;
  s21_create_matrix(2, 2, &B);
  B.matrix[0][0] = 4.4567113;
  B.matrix[0][1] = 8.0987123;
  B.matrix[1][0] = -8.2346861;
  B.matrix[1][1] = -0.9678832;
  s21_create_matrix(2, 2, &orig_result);
  orig_result.matrix[0][0] = 6.9135003;
  orig_result.matrix[0][1] = 2.811764;
  orig_result.matrix[1][0] = -2.1235526;
  orig_result.matrix[1][1] = -4.8971761;
  int my_error = s21_sum_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_sum_test5) {
  matrix_t A, B, result, orig_result;
  s21_create_matrix(4, 4, &A);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = i + 1;
    }
  }
  s21_create_matrix(4, 4, &B);
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = i + 1;
    }
  }
  s21_create_matrix(4, 4, &orig_result);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      orig_result.matrix[i][j] = (i + 1) * 2;
    }
  }
  int my_error = s21_sum_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_int_eq(orig_result.matrix[i][j], result.matrix[i][j]);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_sum_test6) {
  matrix_t A, B, result, orig_result;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 0.1;
  A.matrix[0][1] = 0.2;
  A.matrix[0][2] = 0.3;
  A.matrix[1][0] = 0.4;
  A.matrix[1][1] = 0.5;
  A.matrix[1][2] = 0.6;
  A.matrix[2][0] = 0.7;
  A.matrix[2][1] = 0.8;
  A.matrix[2][2] = 0.9;
  s21_create_matrix(3, 3, &B);
  B.matrix[0][0] = -1.0;
  B.matrix[0][1] = -2.0;
  B.matrix[0][2] = -3.0;
  B.matrix[1][0] = -4.0;
  B.matrix[1][1] = -5.0;
  B.matrix[1][2] = -6.0;
  B.matrix[2][0] = -7.0;
  B.matrix[2][1] = -8.0;
  B.matrix[2][2] = -9.0;
  s21_create_matrix(3, 3, &orig_result);
  orig_result.matrix[0][0] = -0.9;
  orig_result.matrix[0][1] = -1.8;
  orig_result.matrix[0][2] = -2.7;
  orig_result.matrix[1][0] = -3.6;
  orig_result.matrix[1][1] = -4.5;
  orig_result.matrix[1][2] = -5.4;
  orig_result.matrix[2][0] = -6.3;
  orig_result.matrix[2][1] = -7.2;
  orig_result.matrix[2][2] = -8.1;
  int my_error = s21_sum_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_sum_test7) {
  matrix_t A, B, result;
  s21_create_matrix(2, 7, &A);
  A.matrix[0][0] = -9.0;
  A.matrix[0][1] = -13.2;
  A.matrix[0][2] = 8.88;
  A.matrix[0][3] = -15.76;
  A.matrix[0][4] = -5.3;
  A.matrix[0][5] = 5.2;
  A.matrix[0][6] = 6.345;
  A.matrix[1][0] = -4.0;
  A.matrix[1][1] = 8.04;
  A.matrix[1][2] = -6.5;
  A.matrix[1][3] = 2.33;
  A.matrix[1][4] = -0.1;
  A.matrix[1][5] = -7.28;
  A.matrix[1][6] = 6.1;
  s21_create_matrix(2, 7, &B);
  B.matrix[0][0] = 8.0;
  B.matrix[0][1] = 12.2;
  B.matrix[0][2] = -9.88;
  B.matrix[0][3] = 14.76;
  B.matrix[0][4] = 4.3;
  B.matrix[0][5] = -6.2;
  B.matrix[0][6] = -7.345;
  B.matrix[1][0] = 3.0;
  B.matrix[1][1] = -9.04;
  B.matrix[1][2] = 5.5;
  B.matrix[1][3] = -3.33;
  B.matrix[1][4] = -0.9;
  B.matrix[1][5] = 6.28;
  B.matrix[1][6] = -7.1;
  int my_error = s21_sum_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      ck_assert_int_eq(result.matrix[i][j], -1);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(s21_sum_test8) {
  matrix_t A, B, result;
  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 33.4;
  A.matrix[0][1] = -11.678;
  A.matrix[1][0] = 0;
  A.matrix[1][1] = -82.111;
  s21_create_matrix(2, 2, &B);
  B.matrix[0][0] = -33.4;
  B.matrix[0][1] = 11.678;
  B.matrix[1][0] = 0;
  B.matrix[1][1] = 82.11;
  int my_error = s21_sum_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      ck_assert_int_eq(result.matrix[i][j], 0);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(s21_sum_error_test1) {
  matrix_t A, B, result;
  s21_create_matrix(1, 2, &A);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 1;
  s21_create_matrix(2, 2, &B);
  B.matrix[0][0] = 2;
  B.matrix[0][1] = 2;
  B.matrix[1][0] = 2;
  B.matrix[1][1] = 2;
  int my_error = s21_sum_matrix(&A, &B, &result);
  int orig_error = 2;
  ck_assert_int_eq(my_error, orig_error);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_sum_error_test2) {
  matrix_t A, B, result;
  s21_create_matrix(-2, 2, &A);
  s21_create_matrix(2, 2, &B);
  int my_error = s21_sum_matrix(&A, &B, &result);
  int orig_error = 1;
  ck_assert_int_eq(my_error, orig_error);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_sub_test1) {
  matrix_t A, B, result;
  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 0;
  A.matrix[0][1] = 0;
  A.matrix[1][0] = 0;
  A.matrix[1][1] = 0;
  s21_create_matrix(2, 2, &B);
  B.matrix[0][0] = 0;
  B.matrix[0][1] = 0;
  B.matrix[1][0] = 0;
  B.matrix[1][1] = 0;
  int my_error = s21_sub_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      ck_assert_int_eq(result.matrix[i][j], 0);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(s21_sub_test2) {
  matrix_t A, B, result, orig_result;
  s21_create_matrix(4, 4, &A);
  A.matrix[0][0] = 2.5678998;
  A.matrix[0][1] = 1.345001;
  A.matrix[0][2] = 7.09;
  A.matrix[0][3] = -2.5676509;
  A.matrix[1][0] = 9.056;
  A.matrix[1][1] = 3.714;
  A.matrix[1][2] = 4.05;
  A.matrix[1][3] = 1.567;
  A.matrix[2][0] = 3.234;
  A.matrix[2][1] = -1.905;
  A.matrix[2][2] = -7.863;
  A.matrix[2][3] = -1.0987669;
  A.matrix[3][0] = 10.0;
  A.matrix[3][1] = 3.099;
  A.matrix[3][2] = 8.11;
  A.matrix[3][3] = -7.56903;
  s21_create_matrix(4, 4, &B);
  B.matrix[0][0] = 1.12345;
  B.matrix[0][1] = 5.90;
  B.matrix[0][2] = 3.456;
  B.matrix[0][3] = 5.10906;
  B.matrix[1][0] = -5.2345;
  B.matrix[1][1] = 5.2345;
  B.matrix[1][2] = 1.0945;
  B.matrix[1][3] = 8.1234;
  B.matrix[2][0] = 7.098;
  B.matrix[2][1] = 3.01232;
  B.matrix[2][2] = 5.089;
  B.matrix[2][3] = -2.3456;
  B.matrix[3][0] = 7.569;
  B.matrix[3][1] = 3.23089;
  B.matrix[3][2] = 9.087;
  B.matrix[3][3] = -3.0;
  s21_create_matrix(4, 4, &orig_result);
  orig_result.matrix[0][0] = 1.4444498;
  orig_result.matrix[0][1] = -4.554999;
  orig_result.matrix[0][2] = 3.634;
  orig_result.matrix[0][3] = -7.6767109;
  orig_result.matrix[1][0] = 14.2905;
  orig_result.matrix[1][1] = -1.5205;
  orig_result.matrix[1][2] = 2.9555;
  orig_result.matrix[1][3] = -6.5564;
  orig_result.matrix[2][0] = -3.864;
  orig_result.matrix[2][1] = -4.91732;
  orig_result.matrix[2][2] = -12.952;
  orig_result.matrix[2][3] = 1.2468331;
  orig_result.matrix[3][0] = 2.431;
  orig_result.matrix[3][1] = -0.13189;
  orig_result.matrix[3][2] = -0.977;
  orig_result.matrix[3][3] = -4.56903;
  int my_error = s21_sub_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_sub_test3) {
  matrix_t A, B, result, orig_result;
  s21_create_matrix(2, 4, &A);
  A.matrix[0][0] = -9.0;
  A.matrix[0][1] = -13.2;
  A.matrix[0][2] = -8.88;
  A.matrix[0][3] = -15.76;
  A.matrix[1][0] = -4.0;
  A.matrix[1][1] = -8.04;
  A.matrix[1][2] = -6.5;
  A.matrix[1][3] = -2.33;
  s21_create_matrix(2, 4, &B);
  B.matrix[0][0] = 8.0;
  B.matrix[0][1] = 12.2;
  B.matrix[0][2] = 9.88;
  B.matrix[0][3] = 14.76;
  B.matrix[1][0] = 3.0;
  B.matrix[1][1] = 9.04;
  B.matrix[1][2] = 5.5;
  B.matrix[1][3] = 3.33;
  s21_create_matrix(2, 4, &orig_result);
  orig_result.matrix[0][0] = -17.0;
  orig_result.matrix[0][1] = -25.4;
  orig_result.matrix[0][2] = -18.76;
  orig_result.matrix[0][3] = -30.52;
  orig_result.matrix[1][0] = -7.0;
  orig_result.matrix[1][1] = -17.08;
  orig_result.matrix[1][2] = -12.0;
  orig_result.matrix[1][3] = -5.66;
  int my_error = s21_sub_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_sub_test4) {
  matrix_t A, B, result, orig_result;
  s21_create_matrix(2, 4, &A);
  A.matrix[0][0] = 25.785;
  A.matrix[0][1] = -13.2;
  A.matrix[0][2] = 8.8898;
  A.matrix[0][3] = -15.76;
  A.matrix[1][0] = 78.1234;
  A.matrix[1][1] = -17.04;
  A.matrix[1][2] = -7.555;
  A.matrix[1][3] = 23.33;
  s21_create_matrix(2, 4, &B);
  B.matrix[0][0] = 0.0;
  B.matrix[0][1] = 0.0;
  B.matrix[0][2] = 0.0;
  B.matrix[0][3] = 0.0;
  B.matrix[1][0] = 0.0;
  B.matrix[1][1] = 0.0;
  B.matrix[1][2] = 0.0;
  B.matrix[1][3] = 0.0;
  s21_create_matrix(2, 4, &orig_result);
  orig_result.matrix[0][0] = 25.785;
  orig_result.matrix[0][1] = -13.2;
  orig_result.matrix[0][2] = 8.8898;
  orig_result.matrix[0][3] = -15.76;
  orig_result.matrix[1][0] = 78.1234;
  orig_result.matrix[1][1] = -17.04;
  orig_result.matrix[1][2] = -7.555;
  orig_result.matrix[1][3] = 23.33;
  int my_error = s21_sub_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_sub_test5) {
  matrix_t A, B, result, orig_result;
  s21_create_matrix(5, 5, &A);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = i * 4;
    }
  }
  s21_create_matrix(5, 5, &B);
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = i * 2;
    }
  }
  s21_create_matrix(5, 5, &orig_result);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      orig_result.matrix[i][j] = i * 2;
    }
  }
  int my_error = s21_sub_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_sub_test6) {
  matrix_t A, B, result, orig_result;
  s21_create_matrix(4, 4, &A);
  A.matrix[0][0] = 2.5678998;
  A.matrix[0][1] = 1.345001;
  A.matrix[0][2] = 7.09;
  A.matrix[0][3] = 2.5676509;
  A.matrix[1][0] = 9.056;
  A.matrix[1][1] = 3.714;
  A.matrix[1][2] = 4.05;
  A.matrix[1][3] = 1.567;
  A.matrix[2][0] = 3.234;
  A.matrix[2][1] = 1.905;
  A.matrix[2][2] = 7.863;
  A.matrix[2][3] = 1.0987669;
  A.matrix[3][0] = 10.0;
  A.matrix[3][1] = 3.099;
  A.matrix[3][2] = 8.11;
  A.matrix[3][3] = 7.56903;
  s21_create_matrix(4, 4, &B);
  B.matrix[0][0] = -1.12345;
  B.matrix[0][1] = -5.90;
  B.matrix[0][2] = -3.456;
  B.matrix[0][3] = -5.10906;
  B.matrix[1][0] = -5.2345;
  B.matrix[1][1] = -5.2345;
  B.matrix[1][2] = -1.0945;
  B.matrix[1][3] = -8.1234;
  B.matrix[2][0] = -7.098;
  B.matrix[2][1] = -3.01232;
  B.matrix[2][2] = -5.089;
  B.matrix[2][3] = -2.3456;
  B.matrix[3][0] = -7.569;
  B.matrix[3][1] = -3.23089;
  B.matrix[3][2] = -9.087;
  B.matrix[3][3] = -3.0;
  s21_create_matrix(4, 4, &orig_result);
  orig_result.matrix[0][0] = 3.6913498;
  orig_result.matrix[0][1] = 7.245001;
  orig_result.matrix[0][2] = 10.546;
  orig_result.matrix[0][3] = 7.6767109;
  orig_result.matrix[1][0] = 14.2905;
  orig_result.matrix[1][1] = 8.9485;
  orig_result.matrix[1][2] = 5.1445;
  orig_result.matrix[1][3] = 9.6904;
  orig_result.matrix[2][0] = 10.332;
  orig_result.matrix[2][1] = 4.91732;
  orig_result.matrix[2][2] = 12.952;
  orig_result.matrix[2][3] = 3.4443669;
  orig_result.matrix[3][0] = 17.569;
  orig_result.matrix[3][1] = 6.32989;
  orig_result.matrix[3][2] = 17.197;
  orig_result.matrix[3][3] = 10.56903;
  int my_error = s21_sub_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_sub_test7) {
  matrix_t A, B, result;
  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 1.5678;
  A.matrix[0][1] = 1.1234567;
  A.matrix[1][0] = 1.890;
  A.matrix[1][1] = 1.4567890;
  s21_create_matrix(2, 2, &B);
  B.matrix[0][0] = 3.5678;
  B.matrix[0][1] = 3.1234567;
  B.matrix[1][0] = 3.890;
  B.matrix[1][1] = 3.4567890;
  int my_error = s21_sub_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      ck_assert_double_eq_tol(result.matrix[i][j], -2.0, EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(s21_sub_test8) {
  matrix_t A, B, result;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = -1.1;
  A.matrix[0][1] = -2.2;
  A.matrix[0][2] = -3.3;
  A.matrix[1][0] = -4.4;
  A.matrix[1][1] = -5.5;
  A.matrix[1][2] = -6.6;
  A.matrix[2][0] = -7.7;
  A.matrix[2][1] = -8.8;
  A.matrix[2][2] = -9.9;
  s21_create_matrix(3, 3, &B);
  B.matrix[0][0] = -1.1;
  B.matrix[0][1] = -2.2;
  B.matrix[0][2] = -3.3;
  B.matrix[1][0] = -4.4;
  B.matrix[1][1] = -5.5;
  B.matrix[1][2] = -6.6;
  B.matrix[2][0] = -7.7;
  B.matrix[2][1] = -8.8;
  B.matrix[2][2] = -9.9;
  int my_error = s21_sub_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      ck_assert_double_eq_tol(result.matrix[i][j], 0, EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(s21_sub_error_test1) {
  matrix_t A, B, result;
  s21_create_matrix(-2, 2, &A);
  s21_create_matrix(2, 2, &B);
  int my_error = s21_sub_matrix(&A, &B, &result);
  int orig_error = 1;
  ck_assert_int_eq(my_error, orig_error);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_sub_error_test2) {
  matrix_t A, B, result;
  s21_create_matrix(1, 2, &A);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 1;
  s21_create_matrix(2, 2, &B);
  B.matrix[0][0] = 3;
  B.matrix[0][1] = 3;
  B.matrix[1][0] = 3;
  B.matrix[1][1] = 3;
  int my_error = s21_sub_matrix(&A, &B, &result);
  int orig_error = 2;
  ck_assert_int_eq(my_error, orig_error);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_mult_number_test1) {
  matrix_t A, result;
  double num = 0.0;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1.1;
  A.matrix[0][1] = 2.2;
  A.matrix[0][2] = 3.3;
  A.matrix[1][0] = 4.4;
  A.matrix[1][1] = 5.5;
  A.matrix[1][2] = 6.6;
  A.matrix[2][0] = 7.7;
  A.matrix[2][1] = 8.8;
  A.matrix[2][2] = 9.9;
  int my_error = s21_mult_number(&A, num, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      ck_assert_double_eq_tol(result.matrix[i][j], 0.0, EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(s21_mult_number_test2) {
  matrix_t A, result, orig_result;
  double num = -2.0;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1.1;
  A.matrix[0][1] = 2.2;
  A.matrix[0][2] = 3.3;
  A.matrix[1][0] = 4.4;
  A.matrix[1][1] = 5.5;
  A.matrix[1][2] = 6.6;
  A.matrix[2][0] = 7.7;
  A.matrix[2][1] = 8.8;
  A.matrix[2][2] = 9.9;
  s21_create_matrix(3, 3, &orig_result);
  orig_result.matrix[0][0] = -2.2;
  orig_result.matrix[0][1] = -4.4;
  orig_result.matrix[0][2] = -6.6;
  orig_result.matrix[1][0] = -8.8;
  orig_result.matrix[1][1] = -11.0;
  orig_result.matrix[1][2] = -13.2;
  orig_result.matrix[2][0] = -15.4;
  orig_result.matrix[2][1] = -17.6;
  orig_result.matrix[2][2] = -19.8;
  int my_error = s21_mult_number(&A, num, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_mult_number_test_3) {
  matrix_t A, result;
  double num = 1.0;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 0.1;
  A.matrix[0][1] = 0.2;
  A.matrix[0][2] = 0.3;
  A.matrix[1][0] = 0.4;
  A.matrix[1][1] = 0.5;
  A.matrix[1][2] = 0.6;
  A.matrix[2][0] = 0.7;
  A.matrix[2][1] = 0.8;
  A.matrix[2][2] = 0.9;
  int my_error = s21_mult_number(&A, num, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      ck_assert_double_eq_tol(result.matrix[i][j], A.matrix[i][j], EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(s21_mult_number_test_4) {
  matrix_t A, result, orig_result;
  double num = -1.25;
  s21_create_matrix(5, 4, &A);
  A.matrix[0][0] = 23.567;
  A.matrix[0][1] = 5.1;
  A.matrix[0][2] = 7.089;
  A.matrix[0][3] = -2.345;
  A.matrix[1][0] = 6.6;
  A.matrix[1][1] = 3.111;
  A.matrix[1][2] = 4.05;
  A.matrix[1][3] = 7.890;
  A.matrix[2][0] = -5.67;
  A.matrix[2][1] = -0.88;
  A.matrix[2][2] = 3.1234;
  A.matrix[2][3] = 1.0;
  A.matrix[3][0] = 10.2;
  A.matrix[3][1] = 6.99;
  A.matrix[3][2] = 8.89;
  A.matrix[3][3] = 0.0;
  A.matrix[4][0] = -3.33;
  A.matrix[4][1] = 3.023;
  A.matrix[4][2] = 1.0;
  A.matrix[4][3] = 5.876;
  s21_create_matrix(5, 4, &orig_result);
  orig_result.matrix[0][0] = -29.45875;
  orig_result.matrix[0][1] = -6.375;
  orig_result.matrix[0][2] = -8.86125;
  orig_result.matrix[0][3] = 2.93125;
  orig_result.matrix[1][0] = -8.25;
  orig_result.matrix[1][1] = -3.88875;
  orig_result.matrix[1][2] = -5.0625;
  orig_result.matrix[1][3] = -9.8625;
  orig_result.matrix[2][0] = 7.0875;
  orig_result.matrix[2][1] = 1.1;
  orig_result.matrix[2][2] = -3.90425;
  orig_result.matrix[2][3] = -1.25;
  orig_result.matrix[3][0] = -12.75;
  orig_result.matrix[3][1] = -8.7375;
  orig_result.matrix[3][2] = -11.1125;
  orig_result.matrix[3][3] = 0.0;
  orig_result.matrix[4][0] = 4.1625;
  orig_result.matrix[4][1] = -3.77875;
  orig_result.matrix[4][2] = -1.25;
  orig_result.matrix[4][3] = -7.345;
  int my_error = s21_mult_number(&A, num, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_mult_number_test_5) {
  matrix_t A, result, orig_result;
  double num = 0.88;
  s21_create_matrix(5, 5, &A);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = (i + 1) * 2;
    }
  }
  s21_create_matrix(5, 5, &orig_result);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      orig_result.matrix[i][j] = (i + 1) * 2 * 0.88;
    }
  }
  int my_error = s21_mult_number(&A, num, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_mult_number_test_6) {
  matrix_t A, result, orig_result;
  double num = -0.01;
  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = -2.987;
  A.matrix[0][1] = -5.345;
  A.matrix[1][0] = -6.23;
  A.matrix[1][1] = -3.921;
  s21_create_matrix(2, 2, &orig_result);
  orig_result.matrix[0][0] = 0.02987;
  orig_result.matrix[0][1] = 0.05345;
  orig_result.matrix[1][0] = 0.0623;
  orig_result.matrix[1][1] = 0.03921;
  int my_error = s21_mult_number(&A, num, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              1e-7);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_mult_number_test_7) {
  matrix_t A, result, orig_result;
  double num = 1.234567;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 2;
  A.matrix[0][2] = 3;
  A.matrix[1][0] = 4;
  A.matrix[1][1] = 5;
  A.matrix[1][2] = 6;
  A.matrix[2][0] = 7;
  A.matrix[2][1] = 8;
  A.matrix[2][2] = 9;
  s21_create_matrix(3, 3, &orig_result);
  orig_result.matrix[0][0] = 1.234567;
  orig_result.matrix[0][1] = 2.469134;
  orig_result.matrix[0][2] = 3.703701;
  orig_result.matrix[1][0] = 4.938268;
  orig_result.matrix[1][1] = 6.172835;
  orig_result.matrix[1][2] = 7.407402;
  orig_result.matrix[2][0] = 8.641969;
  orig_result.matrix[2][1] = 9.876536;
  orig_result.matrix[2][2] = 11.111103;
  int my_error = s21_mult_number(&A, num, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_mult_number_test_8) {
  matrix_t A, result, orig_result;
  double num = 4.75;
  s21_create_matrix(5, 4, &A);
  A.matrix[0][0] = 2;
  A.matrix[0][1] = 5;
  A.matrix[0][2] = 7;
  A.matrix[0][3] = -3;
  A.matrix[1][0] = 6;
  A.matrix[1][1] = 5;
  A.matrix[1][2] = 4;
  A.matrix[1][3] = 11;
  A.matrix[2][0] = 5;
  A.matrix[2][1] = -2;
  A.matrix[2][2] = -13;
  A.matrix[2][3] = -1;
  A.matrix[3][0] = 10;
  A.matrix[3][1] = 3;
  A.matrix[3][2] = 9;
  A.matrix[3][3] = -6;
  A.matrix[4][0] = -3;
  A.matrix[4][1] = 3;
  A.matrix[4][2] = 1;
  A.matrix[4][3] = 5;
  s21_create_matrix(5, 4, &orig_result);
  orig_result.matrix[0][0] = 9.5;
  orig_result.matrix[0][1] = 23.75;
  orig_result.matrix[0][2] = 33.25;
  orig_result.matrix[0][3] = -14.25;
  orig_result.matrix[1][0] = 28.5;
  orig_result.matrix[1][1] = 23.75;
  orig_result.matrix[1][2] = 19;
  orig_result.matrix[1][3] = 52.25;
  orig_result.matrix[2][0] = 23.75;
  orig_result.matrix[2][1] = -9.5;
  orig_result.matrix[2][2] = -61.75;
  orig_result.matrix[2][3] = -4.75;
  orig_result.matrix[3][0] = 47.5;
  orig_result.matrix[3][1] = 14.25;
  orig_result.matrix[3][2] = 42.75;
  orig_result.matrix[3][3] = -28.5;
  orig_result.matrix[4][0] = -14.25;
  orig_result.matrix[4][1] = 14.25;
  orig_result.matrix[4][2] = 4.75;
  orig_result.matrix[4][3] = 23.75;
  int my_error = s21_mult_number(&A, num, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_mult_number_test_9) {
  matrix_t A, result, orig_result;
  double num = 111.0;
  s21_create_matrix(2, 7, &A);
  A.matrix[0][0] = 11.0;
  A.matrix[0][1] = 22.0;
  A.matrix[0][2] = 33.0;
  A.matrix[0][3] = 44.0;
  A.matrix[0][4] = 55.0;
  A.matrix[0][5] = 66.0;
  A.matrix[0][6] = 77.0;
  A.matrix[1][0] = 88.0;
  A.matrix[1][1] = 99.0;
  A.matrix[1][2] = 111.0;
  A.matrix[1][3] = 222.0;
  A.matrix[1][4] = 333.0;
  A.matrix[1][5] = 444.0;
  A.matrix[1][6] = 555.0;
  s21_create_matrix(2, 7, &orig_result);
  orig_result.matrix[0][0] = 1221;
  orig_result.matrix[0][1] = 2442;
  orig_result.matrix[0][2] = 3663;
  orig_result.matrix[0][3] = 4884;
  orig_result.matrix[0][4] = 6105;
  orig_result.matrix[0][5] = 7326;
  orig_result.matrix[0][6] = 8547;
  orig_result.matrix[1][0] = 9768;
  orig_result.matrix[1][1] = 10989;
  orig_result.matrix[1][2] = 12321;
  orig_result.matrix[1][3] = 24642;
  orig_result.matrix[1][4] = 36963;
  orig_result.matrix[1][5] = 49284;
  orig_result.matrix[1][6] = 61605;
  int my_error = s21_mult_number(&A, num, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_mult_number_error_test1) {
  matrix_t A, result;
  double num = 3;
  s21_create_matrix(-2, 3, &A);
  result.matrix = NULL;
  int my_error = s21_mult_number(&A, num, &result);
  int orig_error = 1;
  ck_assert_int_eq(my_error, orig_error);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_mult_matrix_test_1) {
  matrix_t A, B, result, orig_result;
  s21_create_matrix(1, 1, &A);
  A.matrix[0][0] = 3.67;
  s21_create_matrix(1, 1, &B);
  B.matrix[0][0] = 1345;
  s21_create_matrix(1, 1, &orig_result);
  orig_result.matrix[0][0] = 4936.15;
  int my_error = s21_mult_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_mult_matrix_test_2) {
  matrix_t A, B, result, orig_result;
  s21_create_matrix(2, 4, &A);
  A.matrix[0][0] = 1235;
  A.matrix[0][1] = 789;
  A.matrix[0][2] = 356.789;
  A.matrix[0][3] = 111.8905;
  A.matrix[1][0] = 6789;
  A.matrix[1][1] = 367.89;
  A.matrix[1][2] = 9.9991;
  A.matrix[1][3] = 5324;
  s21_create_matrix(4, 3, &B);
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = -1;
    }
  }
  s21_create_matrix(2, 3, &orig_result);
  orig_result.matrix[0][0] = -2492.6795;
  orig_result.matrix[0][1] = -2492.6795;
  orig_result.matrix[0][2] = -2492.6795;
  orig_result.matrix[1][0] = -12490.8891;
  orig_result.matrix[1][1] = -12490.8891;
  orig_result.matrix[1][2] = -12490.8891;
  int my_error = s21_mult_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_mult_matrix_test_3) {
  matrix_t A, B, result, orig_result;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 0;
  A.matrix[0][1] = 9;
  A.matrix[0][2] = 1;
  A.matrix[1][0] = 1;
  A.matrix[1][1] = 3;
  A.matrix[1][2] = 7;
  A.matrix[2][0] = 2;
  A.matrix[2][1] = 7;
  A.matrix[2][2] = 0;
  s21_create_matrix(3, 3, &B);
  B.matrix[0][0] = 0;
  B.matrix[0][1] = 9;
  B.matrix[0][2] = 8;
  B.matrix[1][0] = 0;
  B.matrix[1][1] = 9;
  B.matrix[1][2] = 9;
  B.matrix[2][0] = 1;
  B.matrix[2][1] = 9;
  B.matrix[2][2] = 6;
  s21_create_matrix(3, 3, &orig_result);
  orig_result.matrix[0][0] = 1;
  orig_result.matrix[0][1] = 90;
  orig_result.matrix[0][2] = 87;
  orig_result.matrix[1][0] = 7;
  orig_result.matrix[1][1] = 99;
  orig_result.matrix[1][2] = 77;
  orig_result.matrix[2][0] = 0;
  orig_result.matrix[2][1] = 81;
  orig_result.matrix[2][2] = 79;
  int my_error = s21_mult_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_mult_matrix_test_4) {
  matrix_t A, B, result, orig_result;
  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 1.234567;
  A.matrix[0][1] = 2.345678;
  A.matrix[1][0] = 3.456789;
  A.matrix[1][1] = 4.567890;
  s21_create_matrix(2, 2, &B);
  B.matrix[0][0] = -21.345;
  B.matrix[0][1] = -566.789;
  B.matrix[1][0] = -111.111;
  B.matrix[1][1] = -398.067;
  s21_create_matrix(2, 2, &orig_result);
  orig_result.matrix[0][0] = -286.982460873;
  orig_result.matrix[0][1] = -1633.475999789;
  orig_result.matrix[1][0] = -581.327986995;
  orig_result.matrix[1][1] = -3777.596249151;
  int my_error = s21_mult_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_mult_matrix_test_5) {
  matrix_t A, B, result, orig_result;
  s21_create_matrix(2, 5, &A);
  A.matrix[0][0] = -1.235;
  A.matrix[0][1] = 2.345;
  A.matrix[0][2] = -3.455;
  A.matrix[0][3] = 4.555;
  A.matrix[0][4] = -5;
  A.matrix[1][0] = 6.785;
  A.matrix[1][1] = -7.895;
  A.matrix[1][2] = 8.955;
  A.matrix[1][3] = -9.555;
  A.matrix[1][4] = 10;
  s21_create_matrix(5, 2, &B);
  B.matrix[0][0] = 0;
  B.matrix[0][1] = -123;
  B.matrix[1][0] = -321;
  B.matrix[1][1] = 0;
  B.matrix[2][0] = 0;
  B.matrix[2][1] = -235;
  B.matrix[3][0] = -345;
  B.matrix[3][1] = 0;
  B.matrix[4][0] = 0;
  B.matrix[4][1] = -555;
  s21_create_matrix(2, 2, &orig_result);
  orig_result.matrix[0][0] = -2324.22;
  orig_result.matrix[0][1] = 3738.83;
  orig_result.matrix[1][0] = 5830.77;
  orig_result.matrix[1][1] = -8488.98;
  int my_error = s21_mult_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_mult_matrix_test_6) {
  matrix_t A, B, result;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 2;
  A.matrix[0][2] = 3;
  A.matrix[1][0] = 4;
  A.matrix[1][1] = 5;
  A.matrix[1][2] = 6;
  A.matrix[2][0] = 7;
  A.matrix[2][1] = 8;
  A.matrix[2][2] = 9;
  s21_create_matrix(3, 3, &B);
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = 0.0;
    }
  }
  int my_error = s21_mult_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      ck_assert_double_eq_tol(result.matrix[i][j], 0.0, EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(s21_mult_matrix_test_7) {
  matrix_t A, B, result, orig_result;
  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 2.987;
  A.matrix[0][1] = -5.345;
  A.matrix[1][0] = 6.23;
  A.matrix[1][1] = -3.92;
  s21_create_matrix(2, 4, &B);
  B.matrix[0][0] = 4.88;
  B.matrix[0][1] = 8.097;
  B.matrix[0][2] = 6.091;
  B.matrix[0][3] = -98.7;
  B.matrix[1][0] = -8;
  B.matrix[1][1] = -0.921;
  B.matrix[1][2] = 56.3;
  B.matrix[1][3] = 21;
  s21_create_matrix(2, 4, &orig_result);
  orig_result.matrix[0][0] = 57.33656;
  orig_result.matrix[0][1] = 29.108484;
  orig_result.matrix[0][2] = -282.729683;
  orig_result.matrix[0][3] = -407.0619;
  orig_result.matrix[1][0] = 61.7624;
  orig_result.matrix[1][1] = 54.05463;
  orig_result.matrix[1][2] = -182.74907;
  orig_result.matrix[1][3] = -697.221;
  int my_error = s21_mult_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_mult_matrix_test_8) {
  matrix_t A, B, result, orig_result;
  s21_create_matrix(4, 3, &A);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 3;
  A.matrix[0][2] = 5;
  A.matrix[1][0] = 7;
  A.matrix[1][1] = 9;
  A.matrix[1][2] = 11;
  A.matrix[2][0] = 13;
  A.matrix[2][1] = 15;
  A.matrix[2][2] = 17;
  A.matrix[3][0] = 19;
  A.matrix[3][1] = 21;
  A.matrix[3][2] = 0;
  s21_create_matrix(3, 3, &B);
  B.matrix[0][0] = 0.1;
  B.matrix[0][1] = 0.2;
  B.matrix[0][2] = 0.3;
  B.matrix[1][0] = 0.4;
  B.matrix[1][1] = 0.5;
  B.matrix[1][2] = 0.6;
  B.matrix[2][0] = 0.7;
  B.matrix[2][1] = 0.8;
  B.matrix[2][2] = 0.9;
  s21_create_matrix(4, 3, &orig_result);
  orig_result.matrix[0][0] = 4.8;
  orig_result.matrix[0][1] = 5.7;
  orig_result.matrix[0][2] = 6.6;
  orig_result.matrix[1][0] = 12;
  orig_result.matrix[1][1] = 14.7;
  orig_result.matrix[1][2] = 17.4;
  orig_result.matrix[2][0] = 19.2;
  orig_result.matrix[2][1] = 23.7;
  orig_result.matrix[2][2] = 28.2;
  orig_result.matrix[3][0] = 10.3;
  orig_result.matrix[3][1] = 14.3;
  orig_result.matrix[3][2] = 18.3;
  int my_error = s21_mult_matrix(&A, &B, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_mult_matrix_error_test1) {
  matrix_t A, B, result;
  s21_create_matrix(-2, 3, &A);
  s21_create_matrix(0, 3, &B);
  int my_error = s21_mult_matrix(&A, &B, &result);
  int orig_error = 1;
  ck_assert_int_eq(my_error, orig_error);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_mult_matrix_error_test2) {
  matrix_t A, B, result;
  s21_create_matrix(2, 3, &A);
  A.matrix[0][0] = 0.1;
  A.matrix[0][1] = 0.2;
  A.matrix[0][2] = 0.3;
  A.matrix[1][0] = 0.4;
  A.matrix[1][1] = 0.5;
  A.matrix[1][2] = 0.6;
  s21_create_matrix(4, 4, &B);
  B.matrix[0][0] = 2.5;
  B.matrix[0][1] = 1.3;
  B.matrix[0][2] = 7.9;
  B.matrix[0][3] = 2.7;
  B.matrix[1][0] = 9.0;
  B.matrix[1][1] = 3.7;
  B.matrix[1][2] = 4.5;
  B.matrix[1][3] = 1.5;
  B.matrix[2][0] = 3.2;
  B.matrix[2][1] = 1.9;
  B.matrix[2][2] = 7.8;
  B.matrix[2][3] = 1.6;
  B.matrix[3][0] = 10.0;
  B.matrix[3][1] = 3.9;
  B.matrix[3][2] = 8.1;
  B.matrix[3][3] = 7.9;
  int my_error = s21_mult_matrix(&A, &B, &result);
  int orig_error = 2;
  ck_assert_int_eq(my_error, orig_error);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_transpose_test1) {
  matrix_t A, result, orig_result;
  s21_create_matrix(5, 9, &A);
  s21_create_matrix(9, 5, &orig_result);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = i;
    }
  }
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      orig_result.matrix[i][j] = j;
    }
  }
  int my_error = s21_transpose(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_int_eq(orig_result.matrix[i][j], result.matrix[i][j]);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_transpose_test2) {
  matrix_t A, result, orig_result;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 4;
  A.matrix[0][2] = 7;
  A.matrix[1][0] = 2;
  A.matrix[1][1] = 5;
  A.matrix[1][2] = 8;
  A.matrix[2][0] = 3;
  A.matrix[2][1] = 6;
  A.matrix[2][2] = 9;
  s21_create_matrix(3, 3, &orig_result);
  orig_result.matrix[0][0] = 1;
  orig_result.matrix[0][1] = 2;
  orig_result.matrix[0][2] = 3;
  orig_result.matrix[1][0] = 4;
  orig_result.matrix[1][1] = 5;
  orig_result.matrix[1][2] = 6;
  orig_result.matrix[2][0] = 7;
  orig_result.matrix[2][1] = 8;
  orig_result.matrix[2][2] = 9;
  int my_error = s21_transpose(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_transpose_test3) {
  matrix_t A, result, orig_result;
  s21_create_matrix(2, 4, &A);
  A.matrix[0][0] = 1235;
  A.matrix[0][1] = 789;
  A.matrix[0][2] = 356.789;
  A.matrix[0][3] = 111.8905;
  A.matrix[1][0] = 6789;
  A.matrix[1][1] = 367.89;
  A.matrix[1][2] = 9.9991;
  A.matrix[1][3] = 5324;
  s21_create_matrix(4, 2, &orig_result);
  orig_result.matrix[0][0] = 1235;
  orig_result.matrix[0][1] = 6789;
  orig_result.matrix[1][0] = 789;
  orig_result.matrix[1][1] = 367.89;
  orig_result.matrix[2][0] = 356.789;
  orig_result.matrix[2][1] = 9.9991;
  orig_result.matrix[3][0] = 111.8905;
  orig_result.matrix[3][1] = 5324;
  int my_error = s21_transpose(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_transpose_test4) {
  matrix_t A, result, orig_result;
  s21_create_matrix(2, 4, &A);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = 0.0;
    }
  }
  s21_create_matrix(4, 2, &orig_result);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      orig_result.matrix[i][j] = 0.0;
    }
  }
  int my_error = s21_transpose(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_transpose_test5) {
  matrix_t A, result, orig_result;
  s21_create_matrix(4, 7, &A);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = i;
    }
  }
  s21_create_matrix(7, 4, &orig_result);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      orig_result.matrix[i][j] = j;
    }
  }
  int my_error = s21_transpose(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_transpose_test6) {
  matrix_t A, result, orig_result;
  s21_create_matrix(5, 4, &A);
  A.matrix[0][0] = 2;
  A.matrix[0][1] = 5;
  A.matrix[0][2] = 7;
  A.matrix[0][3] = -4;
  A.matrix[1][0] = 6;
  A.matrix[1][1] = 3;
  A.matrix[1][2] = 4;
  A.matrix[1][3] = 14;
  A.matrix[2][0] = 5;
  A.matrix[2][1] = -2;
  A.matrix[2][2] = -3;
  A.matrix[2][3] = -1;
  A.matrix[3][0] = 10;
  A.matrix[3][1] = 3;
  A.matrix[3][2] = 9;
  A.matrix[3][3] = -3;
  A.matrix[4][0] = -3;
  A.matrix[4][1] = 3;
  A.matrix[4][2] = 1;
  A.matrix[4][3] = 5;
  s21_create_matrix(4, 5, &orig_result);
  orig_result.matrix[0][0] = 2;
  orig_result.matrix[0][1] = 6;
  orig_result.matrix[0][2] = 5;
  orig_result.matrix[0][3] = 10;
  orig_result.matrix[0][4] = -3;
  orig_result.matrix[1][0] = 5;
  orig_result.matrix[1][1] = 3;
  orig_result.matrix[1][2] = -2;
  orig_result.matrix[1][3] = 3;
  orig_result.matrix[1][4] = 3;
  orig_result.matrix[2][0] = 7;
  orig_result.matrix[2][1] = 4;
  orig_result.matrix[2][2] = -3;
  orig_result.matrix[2][3] = 9;
  orig_result.matrix[2][4] = 1;
  orig_result.matrix[3][0] = -4;
  orig_result.matrix[3][1] = 14;
  orig_result.matrix[3][2] = -1;
  orig_result.matrix[3][3] = -3;
  orig_result.matrix[3][4] = 5;
  int my_error = s21_transpose(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_transpose_test7) {
  matrix_t A, result, orig_result;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 9.345678;
  A.matrix[0][1] = -5.67849;
  A.matrix[0][2] = 25.45678;
  A.matrix[1][0] = -10.4567;
  A.matrix[1][1] = 6.9731;
  A.matrix[1][2] = -9.9991;
  A.matrix[2][0] = 7.456732;
  A.matrix[2][1] = -8.67893;
  A.matrix[2][2] = 15.78954;
  s21_create_matrix(3, 3, &orig_result);
  orig_result.matrix[0][0] = 9.345678;
  orig_result.matrix[0][1] = -10.4567;
  orig_result.matrix[0][2] = 7.456732;
  orig_result.matrix[1][0] = -5.67849;
  orig_result.matrix[1][1] = 6.9731;
  orig_result.matrix[1][2] = -8.67893;
  orig_result.matrix[2][0] = 25.45678;
  orig_result.matrix[2][1] = -9.9991;
  orig_result.matrix[2][2] = 15.78954;
  int my_error = s21_transpose(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_transpose_error_test1) {
  matrix_t A, result;
  s21_create_matrix(3, -2, &A);
  int my_error = s21_transpose(&A, &result);
  int orig_error = 1;
  ck_assert_int_eq(my_error, orig_error);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_determinant_test1) {
  matrix_t A;
  double result;
  s21_create_matrix(1, 1, &A);
  A.matrix[0][0] = 7;
  int my_error = s21_determinant(&A, &result);
  int orig_error = 0;
  double orig_result = 7;
  ck_assert_int_eq(my_error, orig_error);
  ck_assert_int_eq(result, orig_result);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_determinant_test2) {
  matrix_t A;
  double result;
  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 8;
  A.matrix[0][1] = 9;
  A.matrix[1][0] = 3;
  A.matrix[1][1] = 4;
  int my_error = s21_determinant(&A, &result);
  int orig_error = 0;
  double orig_result = 5;
  ck_assert_int_eq(my_error, orig_error);
  ck_assert_int_eq(result, orig_result);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_determinant_test3) {
  matrix_t A;
  double result;
  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = -1.234;
  A.matrix[0][1] = 9.088;
  A.matrix[1][0] = 7.91;
  A.matrix[1][1] = -2.002;
  int my_error = s21_determinant(&A, &result);
  int orig_error = 0;
  double orig_result = -69.415612;
  ck_assert_int_eq(my_error, orig_error);
  ck_assert_double_eq_tol(result, orig_result, EPS);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_determinant_test4) {
  matrix_t A;
  double result;
  s21_create_matrix(4, 4, &A);
  A.matrix[0][0] = -1.1;
  A.matrix[0][1] = 2.2;
  A.matrix[0][2] = -3.3;
  A.matrix[0][3] = 4.4;
  A.matrix[1][0] = -5.5;
  A.matrix[1][1] = 6.6;
  A.matrix[1][2] = -7.7;
  A.matrix[1][3] = 8.8;
  A.matrix[2][0] = -9.9;
  A.matrix[2][1] = 10.0;
  A.matrix[2][2] = -11.1;
  A.matrix[2][3] = 12.2;
  A.matrix[3][0] = -13.3;
  A.matrix[3][1] = 14.4;
  A.matrix[3][2] = -15.5;
  A.matrix[3][3] = 16.6;
  int my_error = s21_determinant(&A, &result);
  int orig_error = 0;
  double orig_result = 0;
  ck_assert_int_eq(my_error, orig_error);
  ck_assert_double_eq_tol(result, orig_result, EPS);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_determinant_test5) {
  matrix_t A;
  double result;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 123.456;
  A.matrix[1][0] = 123.455;
  A.matrix[2][0] = 123.454;
  A.matrix[0][1] = 123.453;
  A.matrix[1][1] = 123.452;
  A.matrix[2][1] = 123.451;
  A.matrix[0][2] = 123.450;
  A.matrix[1][2] = 1113.449;
  A.matrix[2][2] = 15.448;
  int my_error = s21_determinant(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  ck_assert_double_eq_tol(result, 0.006264, EPS);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_determinant_test6) {
  matrix_t A;
  double result;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 0.2;
  A.matrix[1][0] = 1.9;
  A.matrix[2][0] = 2.33;
  A.matrix[0][1] = -1.5678;
  A.matrix[1][1] = 0;
  A.matrix[2][1] = 1;
  A.matrix[0][2] = 3;
  A.matrix[1][2] = 1.7;
  A.matrix[2][2] = -3;
  int my_error = s21_determinant(&A, &result);
  int orig_error = 0;
  double orig_result = -9.7865158;
  ck_assert_int_eq(my_error, orig_error);
  ck_assert_double_eq_tol(result, orig_result, EPS);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_determinant_test7) {
  matrix_t A;
  double result;
  s21_create_matrix(5, 5, &A);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = 1;
    }
  }
  int my_error = s21_determinant(&A, &result);
  int orig_error = 0;
  double orig_result = 0;
  ck_assert_int_eq(my_error, orig_error);
  ck_assert_int_eq(result, orig_result);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_determinant_test8) {
  matrix_t A;
  double result;
  s21_create_matrix(7, 7, &A);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = i + 1;
    }
  }
  int my_error = s21_determinant(&A, &result);
  int orig_error = 0;
  double orig_result = 0;
  ck_assert_int_eq(my_error, orig_error);
  ck_assert_int_eq(result, orig_result);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_determinant_test9) {
  matrix_t A;
  double result, orig_result;
  s21_create_matrix(4, 4, &A);
  A.matrix[0][0] = 0;
  A.matrix[0][1] = 2;
  A.matrix[0][2] = 3;
  A.matrix[0][3] = 5;
  A.matrix[1][0] = 3;
  A.matrix[1][1] = 4;
  A.matrix[1][2] = 0;
  A.matrix[1][3] = 4;
  A.matrix[2][0] = 8;
  A.matrix[2][1] = 6;
  A.matrix[2][2] = 0;
  A.matrix[2][3] = 4;
  A.matrix[3][0] = 6;
  A.matrix[3][1] = 8;
  A.matrix[3][2] = 9;
  A.matrix[3][3] = 4;
  int my_error = s21_determinant(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  orig_result = 438.0;
  ck_assert_double_eq_tol(orig_result, result, EPS);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_determinant_test10) {
  matrix_t A;
  double result, orig_result;
  s21_create_matrix(4, 4, &A);
  A.matrix[0][0] = 111;
  A.matrix[0][1] = -111;
  A.matrix[0][2] = 222;
  A.matrix[0][3] = -222;
  A.matrix[1][0] = -22;
  A.matrix[1][1] = 11;
  A.matrix[1][2] = -11;
  A.matrix[1][3] = 22;
  A.matrix[2][0] = 0;
  A.matrix[2][1] = 33;
  A.matrix[2][2] = 1;
  A.matrix[2][3] = -33;
  A.matrix[3][0] = 88;
  A.matrix[3][1] = -9;
  A.matrix[3][2] = -88;
  A.matrix[3][3] = 9;
  int my_error = s21_determinant(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  orig_result = -32967.0;
  ck_assert_double_eq_tol(orig_result, result, EPS);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_determinant_test11) {
  matrix_t A;
  double result, orig_result;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 0.788;
  A.matrix[0][1] = 1.34;
  A.matrix[0][2] = 0.02;
  A.matrix[1][0] = 0.45;
  A.matrix[1][1] = 0.111;
  A.matrix[1][2] = 1.0;
  A.matrix[2][0] = 1.99;
  A.matrix[2][1] = 0.99;
  A.matrix[2][2] = 0.56;
  int my_error = s21_determinant(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  orig_result = 40056857.0 / 25000000.0;
  ck_assert_double_eq_tol(orig_result, result, EPS);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_determinant_error_test1) {
  matrix_t A;
  double result;
  s21_create_matrix(5, 4, &A);
  int my_error = s21_determinant(&A, &result);
  int orig_error = 2;
  ck_assert_int_eq(my_error, orig_error);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_determinant_error_test2) {
  matrix_t A;
  double result;
  s21_create_matrix(-2, 4, &A);
  int my_error = s21_determinant(&A, &result);
  int orig_error = 1;
  ck_assert_int_eq(my_error, orig_error);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_calc_complements_test1) {
  matrix_t A, result, orig_result;
  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 2;
  A.matrix[0][1] = 4;
  A.matrix[1][0] = 6;
  A.matrix[1][1] = 3;
  s21_create_matrix(2, 2, &orig_result);
  orig_result.matrix[0][0] = 3;
  orig_result.matrix[0][1] = -6;
  orig_result.matrix[1][0] = -4;
  orig_result.matrix[1][1] = 2;
  int my_error = s21_calc_complements(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_calc_complements_test2) {
  matrix_t A, result, orig_result;
  s21_create_matrix(1, 1, &A);
  A.matrix[0][0] = -234;
  s21_create_matrix(1, 1, &orig_result);
  orig_result.matrix[0][0] = 1;
  int my_error = s21_calc_complements(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_calc_complements_test3) {
  matrix_t A, result, orig_result;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 2;
  A.matrix[0][2] = 3;
  A.matrix[1][0] = 0;
  A.matrix[1][1] = 4;
  A.matrix[1][2] = 2;
  A.matrix[2][0] = 5;
  A.matrix[2][1] = 2;
  A.matrix[2][2] = 1;
  s21_create_matrix(3, 3, &orig_result);
  orig_result.matrix[0][0] = 0;
  orig_result.matrix[0][1] = 10;
  orig_result.matrix[0][2] = -20;
  orig_result.matrix[1][0] = 4;
  orig_result.matrix[1][1] = -14;
  orig_result.matrix[1][2] = 8;
  orig_result.matrix[2][0] = -8;
  orig_result.matrix[2][1] = -2;
  orig_result.matrix[2][2] = 4;
  int my_error = s21_calc_complements(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_calc_complements_test4) {
  matrix_t A, result, orig_result;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 2;
  A.matrix[0][1] = 9;
  A.matrix[0][2] = -3;
  A.matrix[1][0] = 10;
  A.matrix[1][1] = -9;
  A.matrix[1][2] = 7;
  A.matrix[2][0] = -1;
  A.matrix[2][1] = 2;
  A.matrix[2][2] = 6;
  s21_create_matrix(3, 3, &orig_result);
  orig_result.matrix[0][0] = -68;
  orig_result.matrix[0][1] = -67;
  orig_result.matrix[0][2] = 11;
  orig_result.matrix[1][0] = -60;
  orig_result.matrix[1][1] = 9;
  orig_result.matrix[1][2] = -13;
  orig_result.matrix[2][0] = 36;
  orig_result.matrix[2][1] = -44;
  orig_result.matrix[2][2] = -108;
  int my_error = s21_calc_complements(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_calc_complements_test5) {
  matrix_t A, result, orig_result;
  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = -234.567;
  A.matrix[0][1] = -99.9999;
  A.matrix[1][0] = -111.345;
  A.matrix[1][1] = -789.897;
  s21_create_matrix(2, 2, &orig_result);
  orig_result.matrix[0][0] = -789.897;
  orig_result.matrix[0][1] = 111.345;
  orig_result.matrix[1][0] = 99.9999;
  orig_result.matrix[1][1] = -234.567;
  int my_error = s21_calc_complements(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_calc_complements_test6) {
  matrix_t A, result, orig_result;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 123;
  A.matrix[0][1] = 231;
  A.matrix[0][2] = 321;
  A.matrix[1][0] = 456;
  A.matrix[1][1] = 564;
  A.matrix[1][2] = 654;
  A.matrix[2][0] = 789;
  A.matrix[2][1] = 879;
  A.matrix[2][2] = 987;
  s21_create_matrix(3, 3, &orig_result);
  orig_result.matrix[0][0] = -18198;
  orig_result.matrix[0][1] = 65934;
  orig_result.matrix[0][2] = -44172;
  orig_result.matrix[1][0] = 54162;
  orig_result.matrix[1][1] = -131868;
  orig_result.matrix[1][2] = 74142;
  orig_result.matrix[2][0] = -29970;
  orig_result.matrix[2][1] = 65934;
  orig_result.matrix[2][2] = -35964;
  int my_error = s21_calc_complements(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_calc_complements_test7) {
  matrix_t A, result, orig_result;
  s21_create_matrix(4, 4, &A);
  A.matrix[0][0] = 111;
  A.matrix[0][1] = -111;
  A.matrix[0][2] = 222;
  A.matrix[0][3] = -222;
  A.matrix[1][0] = -22;
  A.matrix[1][1] = 11;
  A.matrix[1][2] = -11;
  A.matrix[1][3] = 22;
  A.matrix[2][0] = 0;
  A.matrix[2][1] = 33;
  A.matrix[2][2] = 1;
  A.matrix[2][3] = -33;
  A.matrix[3][0] = 88;
  A.matrix[3][1] = -9;
  A.matrix[3][2] = -88;
  A.matrix[3][3] = 9;
  s21_create_matrix(4, 4, &orig_result);
  orig_result.matrix[0][0] = -95535;
  orig_result.matrix[0][1] = -93698;
  orig_result.matrix[0][2] = -95832;
  orig_result.matrix[0][3] = -96602;
  orig_result.matrix[1][0] = -964035;
  orig_result.matrix[1][1] = -946497;
  orig_result.matrix[1][2] = -967032;
  orig_result.matrix[1][3] = -975801;
  orig_result.matrix[2][0] = -32967;
  orig_result.matrix[2][1] = -32967;
  orig_result.matrix[2][2] = -32967;
  orig_result.matrix[2][3] = -32967;
  orig_result.matrix[3][0] = -120879;
  orig_result.matrix[3][1] = -118437;
  orig_result.matrix[3][2] = -120879;
  orig_result.matrix[3][3] = -122100;
  int my_error = s21_calc_complements(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_calc_complements_test8) {
  matrix_t A, result, orig_result;
  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 111111.1;
  A.matrix[0][1] = 333333.3;
  A.matrix[1][0] = 232323.2;
  A.matrix[1][1] = 111111.1;
  s21_create_matrix(2, 2, &orig_result);
  orig_result.matrix[0][0] = 111111.1;
  orig_result.matrix[0][1] = -232323.2;
  orig_result.matrix[1][0] = -333333.3;
  orig_result.matrix[1][1] = 111111.1;
  int my_error = s21_calc_complements(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_calc_complements_test9) {
  matrix_t A, result, orig_result;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 0.78889;
  A.matrix[0][1] = 1.3456;
  A.matrix[0][2] = 0.0234;
  A.matrix[1][0] = 0.456731;
  A.matrix[1][1] = 0.111111;
  A.matrix[1][2] = 1.00034;
  A.matrix[2][0] = 1.99999;
  A.matrix[2][1] = 0.99112;
  A.matrix[2][2] = 0.567723;
  s21_create_matrix(3, 3, &orig_result);
  orig_result.matrix[0][0] = -0.928376710547;
  orig_result.matrix[0][1] = 1.741373303087;
  orig_result.matrix[0][2] = 0.23045433983;
  orig_result.matrix[1][0] = -0.7407358608;
  orig_result.matrix[1][1] = 0.40107123147;
  orig_result.matrix[1][2] = 1.9093018872;
  orig_result.matrix[2][0] = 1.3434575066;
  orig_result.matrix[2][1] = -0.7784707172;
  orig_result.matrix[2][2] = -0.52692287681;
  int my_error = s21_calc_complements(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_calc_complements_error_test1) {
  matrix_t A, result;
  s21_create_matrix(3, 2, &A);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = i;
    }
  }
  int my_error = s21_calc_complements(&A, &result);
  int orig_error = 2;
  ck_assert_int_eq(my_error, orig_error);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_calc_complements_error_test2) {
  matrix_t A, result;
  s21_create_matrix(-2, 2, &A);
  int my_error = s21_calc_complements(&A, &result);
  int orig_error = 1;
  ck_assert_int_eq(my_error, orig_error);
}
END_TEST

START_TEST(s21_inverse_matrix_test1) {
  matrix_t A, result, orig_result;
  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = -234.567;
  A.matrix[0][1] = -99.9999;
  A.matrix[1][0] = -111.345;
  A.matrix[1][1] = -789.897;
  s21_create_matrix(2, 2, &orig_result);
  orig_result.matrix[0][0] = -526598000.0 / 116099520489.0;
  orig_result.matrix[0][1] = 7407400.0 / 12899946721.0;
  orig_result.matrix[1][0] = 74230000.0 / 116099520489.0;
  orig_result.matrix[1][1] = -52126000.0 / 38699840163.0;
  int my_error = s21_inverse_matrix(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_inverse_matrix_test2) {
  matrix_t A, result, orig_result;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 2;
  A.matrix[0][1] = 9;
  A.matrix[0][2] = -3;
  A.matrix[1][0] = 10;
  A.matrix[1][1] = -9;
  A.matrix[1][2] = 7;
  A.matrix[2][0] = -1;
  A.matrix[2][1] = 2;
  A.matrix[2][2] = 6;
  s21_create_matrix(3, 3, &orig_result);
  orig_result.matrix[0][0] = 17.0 / 193.0;
  orig_result.matrix[0][1] = 15.0 / 193.0;
  orig_result.matrix[0][2] = -9.0 / 193.0;
  orig_result.matrix[1][0] = 67.0 / 772.0;
  orig_result.matrix[1][1] = -9.0 / 772.0;
  orig_result.matrix[1][2] = 11.0 / 193.0;
  orig_result.matrix[2][0] = -11.0 / 772.0;
  orig_result.matrix[2][1] = 13.0 / 772.0;
  orig_result.matrix[2][2] = 27.0 / 193.0;
  int my_error = s21_inverse_matrix(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_inverse_matrix_test3) {
  matrix_t A, result, orig_result;
  s21_create_matrix(1, 1, &A);
  A.matrix[0][0] = 6893;
  s21_create_matrix(1, 1, &orig_result);
  orig_result.matrix[0][0] = 1.0 / 6893.0;
  int my_error = s21_inverse_matrix(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  ck_assert_double_eq_tol(orig_result.matrix[0][0], result.matrix[0][0], EPS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_inverse_matrix_test4) {
  matrix_t A, result, orig_result;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 123;
  A.matrix[0][1] = 231;
  A.matrix[0][2] = 321;
  A.matrix[1][0] = 456;
  A.matrix[1][1] = 564;
  A.matrix[1][2] = 654;
  A.matrix[2][0] = 789;
  A.matrix[2][1] = 879;
  A.matrix[2][2] = 987;
  s21_create_matrix(3, 3, &orig_result);
  orig_result.matrix[0][0] = 337.0 / 21978.0;
  orig_result.matrix[0][1] = -1003.0 / 21978.0;
  orig_result.matrix[0][2] = 5.0 / 198.0;
  orig_result.matrix[1][0] = -1.0 / 18.0;
  orig_result.matrix[1][1] = 1.0 / 9.0;
  orig_result.matrix[1][2] = -1.0 / 18.0;
  orig_result.matrix[2][0] = 409.0 / 10989.0;
  orig_result.matrix[2][1] = -1373.0 / 21978.0;
  orig_result.matrix[2][2] = 1.0 / 33.0;
  int my_error = s21_inverse_matrix(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_inverse_matrix_test5) {
  matrix_t A, result, orig_result;
  s21_create_matrix(4, 4, &A);
  A.matrix[0][0] = 111;
  A.matrix[0][1] = -111;
  A.matrix[0][2] = 222;
  A.matrix[0][3] = -222;
  A.matrix[1][0] = -22;
  A.matrix[1][1] = 11;
  A.matrix[1][2] = -11;
  A.matrix[1][3] = 22;
  A.matrix[2][0] = 0;
  A.matrix[2][1] = 33;
  A.matrix[2][2] = 1;
  A.matrix[2][3] = -33;
  A.matrix[3][0] = 88;
  A.matrix[3][1] = -9;
  A.matrix[3][2] = -88;
  A.matrix[3][3] = 9;
  s21_create_matrix(4, 4, &orig_result);
  orig_result.matrix[0][0] = 965.0 / 333.0;
  orig_result.matrix[0][1] = 965.0 / 33.0;
  orig_result.matrix[0][2] = 1.0;
  orig_result.matrix[0][3] = 11.0 / 3.0;
  orig_result.matrix[1][0] = 8518.0 / 2997.0;
  orig_result.matrix[1][1] = 8527.0 / 297.0;
  orig_result.matrix[1][2] = 1.0;
  orig_result.matrix[1][3] = 97.0 / 27.0;
  orig_result.matrix[2][0] = 968.0 / 333.0;
  orig_result.matrix[2][1] = 88.0 / 3.0;
  orig_result.matrix[2][2] = 1.0;
  orig_result.matrix[2][3] = 11.0 / 3.0;
  orig_result.matrix[3][0] = 8782.0 / 2997.0;
  orig_result.matrix[3][1] = 8791.0 / 297.0;
  orig_result.matrix[3][2] = 1.0;
  orig_result.matrix[3][3] = 100.0 / 27.0;
  int my_error = s21_inverse_matrix(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_inverse_matrix_test6) {
  matrix_t A, result, orig_result;
  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 111111.1;
  A.matrix[0][1] = 333333.3;
  A.matrix[1][0] = 232323.2;
  A.matrix[1][1] = 111111.1;
  s21_create_matrix(2, 2, &orig_result);
  orig_result.matrix[0][0] = -2.0 / 1171717.0;
  orig_result.matrix[0][1] = 6.0 / 1171717.0;
  orig_result.matrix[1][0] = 4646464.0 / 1301907647587.0;
  orig_result.matrix[1][1] = -2.0 / 1171717.0;
  int my_error = s21_inverse_matrix(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_inverse_matrix_test7) {
  matrix_t A, result, orig_result;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 0.788;
  A.matrix[0][1] = 1.34;
  A.matrix[0][2] = 0.02;
  A.matrix[1][0] = 0.45;
  A.matrix[1][1] = 0.111;
  A.matrix[1][2] = 1.0;
  A.matrix[2][0] = 1.99;
  A.matrix[2][1] = 0.99;
  A.matrix[2][2] = 0.56;
  s21_create_matrix(3, 3, &orig_result);
  orig_result.matrix[0][0] = -23196000.0 / 40056857.0;
  orig_result.matrix[0][1] = -18265000.0 / 40056857.0;
  orig_result.matrix[0][2] = 33444500.0 / 40056857.0;
  orig_result.matrix[1][0] = 43450000.0 / 40056857.0;
  orig_result.matrix[1][1] = 10037000.0 / 40056857.0;
  orig_result.matrix[1][2] = -19475000.0 / 40056857.0;
  orig_result.matrix[2][0] = 5615250.0 / 40056857.0;
  orig_result.matrix[2][1] = 47162000.0 / 40056857.0;
  orig_result.matrix[2][2] = -12888300.0 / 40056857.0;
  int my_error = s21_inverse_matrix(&A, &result);
  int orig_error = 0;
  ck_assert_int_eq(my_error, orig_error);
  for (int i = 0; i < orig_result.rows; i++) {
    for (int j = 0; j < orig_result.columns; j++) {
      ck_assert_double_eq_tol(orig_result.matrix[i][j], result.matrix[i][j],
                              EPS);
    }
  }
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&orig_result);
}
END_TEST

START_TEST(s21_inverse_matrix_error_test1) {
  matrix_t A, result;
  s21_create_matrix(4, 4, &A);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = i + 1;
    }
  }
  int my_error = s21_inverse_matrix(&A, &result);
  int orig_error = 2;
  ck_assert_int_eq(my_error, orig_error);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_inverse_matrix_error_test2) {
  matrix_t A, result;
  s21_create_matrix(3, 2, &A);
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = i;
    }
  }
  int my_error = s21_inverse_matrix(&A, &result);
  int orig_error = 2;
  ck_assert_int_eq(my_error, orig_error);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_inverse_matrix_error_test3) {
  matrix_t A, result;
  s21_create_matrix(-2, 2, &A);
  int my_error = s21_inverse_matrix(&A, &result);
  int orig_error = 1;
  ck_assert_int_eq(my_error, orig_error);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_create_test1);
  tcase_add_test(tc1_1, s21_create_test2);
  tcase_add_test(tc1_1, s21_create_test3);
  tcase_add_test(tc1_1, s21_create_error_test1);
  tcase_add_test(tc1_1, s21_create_error_test2);
  tcase_add_test(tc1_1, s21_equal_test1);
  tcase_add_test(tc1_1, s21_equal_test2);
  tcase_add_test(tc1_1, s21_equal_test3);
  tcase_add_test(tc1_1, s21_equal_test4);
  tcase_add_test(tc1_1, s21_equal_test5);
  tcase_add_test(tc1_1, s21_equal_test6);
  tcase_add_test(tc1_1, s21_equal_test7);
  tcase_add_test(tc1_1, s21_equal_test8);
  tcase_add_test(tc1_1, s21_equal_test9);
  tcase_add_test(tc1_1, s21_equal_test10);
  tcase_add_test(tc1_1, s21_sum_test1);
  tcase_add_test(tc1_1, s21_sum_test2);
  tcase_add_test(tc1_1, s21_sum_test3);
  tcase_add_test(tc1_1, s21_sum_test4);
  tcase_add_test(tc1_1, s21_sum_test5);
  tcase_add_test(tc1_1, s21_sum_test6);
  tcase_add_test(tc1_1, s21_sum_test7);
  tcase_add_test(tc1_1, s21_sum_test8);
  tcase_add_test(tc1_1, s21_sum_error_test1);
  tcase_add_test(tc1_1, s21_sum_error_test2);
  tcase_add_test(tc1_1, s21_sub_test1);
  tcase_add_test(tc1_1, s21_sub_test2);
  tcase_add_test(tc1_1, s21_sub_test3);
  tcase_add_test(tc1_1, s21_sub_test4);
  tcase_add_test(tc1_1, s21_sub_test5);
  tcase_add_test(tc1_1, s21_sub_test6);
  tcase_add_test(tc1_1, s21_sub_test7);
  tcase_add_test(tc1_1, s21_sub_test8);
  tcase_add_test(tc1_1, s21_sub_error_test1);
  tcase_add_test(tc1_1, s21_sub_error_test2);
  tcase_add_test(tc1_1, s21_mult_number_test1);
  tcase_add_test(tc1_1, s21_mult_number_test2);
  tcase_add_test(tc1_1, s21_mult_number_test_3);
  tcase_add_test(tc1_1, s21_mult_number_test_4);
  tcase_add_test(tc1_1, s21_mult_number_test_5);
  tcase_add_test(tc1_1, s21_mult_number_test_6);
  tcase_add_test(tc1_1, s21_mult_number_test_7);
  tcase_add_test(tc1_1, s21_mult_number_test_8);
  tcase_add_test(tc1_1, s21_mult_number_test_9);
  tcase_add_test(tc1_1, s21_mult_number_error_test1);
  tcase_add_test(tc1_1, s21_mult_matrix_test_1);
  tcase_add_test(tc1_1, s21_mult_matrix_test_2);
  tcase_add_test(tc1_1, s21_mult_matrix_test_3);
  tcase_add_test(tc1_1, s21_mult_matrix_test_4);
  tcase_add_test(tc1_1, s21_mult_matrix_test_5);
  tcase_add_test(tc1_1, s21_mult_matrix_test_6);
  tcase_add_test(tc1_1, s21_mult_matrix_test_7);
  tcase_add_test(tc1_1, s21_mult_matrix_test_8);
  tcase_add_test(tc1_1, s21_mult_matrix_error_test1);
  tcase_add_test(tc1_1, s21_mult_matrix_error_test2);
  tcase_add_test(tc1_1, s21_transpose_test1);
  tcase_add_test(tc1_1, s21_transpose_test2);
  tcase_add_test(tc1_1, s21_transpose_test3);
  tcase_add_test(tc1_1, s21_transpose_test4);
  tcase_add_test(tc1_1, s21_transpose_test5);
  tcase_add_test(tc1_1, s21_transpose_test6);
  tcase_add_test(tc1_1, s21_transpose_test7);
  tcase_add_test(tc1_1, s21_transpose_error_test1);
  tcase_add_test(tc1_1, s21_determinant_test1);
  tcase_add_test(tc1_1, s21_determinant_test2);
  tcase_add_test(tc1_1, s21_determinant_test3);
  tcase_add_test(tc1_1, s21_determinant_test4);
  tcase_add_test(tc1_1, s21_determinant_test5);
  tcase_add_test(tc1_1, s21_determinant_test6);
  tcase_add_test(tc1_1, s21_determinant_test7);
  tcase_add_test(tc1_1, s21_determinant_test8);
  tcase_add_test(tc1_1, s21_determinant_test9);
  tcase_add_test(tc1_1, s21_determinant_test10);
  tcase_add_test(tc1_1, s21_determinant_test11);
  tcase_add_test(tc1_1, s21_determinant_error_test1);
  tcase_add_test(tc1_1, s21_determinant_error_test2);
  tcase_add_test(tc1_1, s21_calc_complements_test1);
  tcase_add_test(tc1_1, s21_calc_complements_test2);
  tcase_add_test(tc1_1, s21_calc_complements_test3);
  tcase_add_test(tc1_1, s21_calc_complements_test4);
  tcase_add_test(tc1_1, s21_calc_complements_test5);
  tcase_add_test(tc1_1, s21_calc_complements_test6);
  tcase_add_test(tc1_1, s21_calc_complements_test7);
  tcase_add_test(tc1_1, s21_calc_complements_test8);
  tcase_add_test(tc1_1, s21_calc_complements_test9);
  tcase_add_test(tc1_1, s21_calc_complements_error_test1);
  tcase_add_test(tc1_1, s21_calc_complements_error_test2);
  tcase_add_test(tc1_1, s21_inverse_matrix_test1);
  tcase_add_test(tc1_1, s21_inverse_matrix_test2);
  tcase_add_test(tc1_1, s21_inverse_matrix_test3);
  tcase_add_test(tc1_1, s21_inverse_matrix_test4);
  tcase_add_test(tc1_1, s21_inverse_matrix_test5);
  tcase_add_test(tc1_1, s21_inverse_matrix_test6);
  tcase_add_test(tc1_1, s21_inverse_matrix_test7);
  tcase_add_test(tc1_1, s21_inverse_matrix_error_test1);
  tcase_add_test(tc1_1, s21_inverse_matrix_error_test2);
  tcase_add_test(tc1_1, s21_inverse_matrix_error_test3);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
